import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import { MainProvider } from '@/shared/providers/main.provider';
import '@/shared/scss/swiper.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap');
        </style>
      </head>
      <body>
        <MainProvider>
          <div className="wrapper">
            <div id='smooth-content'>{children}</div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
