import type { Metadata } from 'next';
import './globals.css';
import { MainProvider } from '@/shared/providers/main.provider';
import '@/shared/scss/swiper.scss';
import { Footer, Header } from '@/widgets';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url(&quot;https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap&quot;);
        </style>
      </head>
      <body>
        <MainProvider>
          <Header />
          <div className="wrapper">
            <div id="smooth-content">
              {children}
              <Footer />
            </div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
