import type { Metadata } from 'next';
import './globals.css';
import { MainProvider } from '@/shared/providers/main.provider';
import '@/shared/scss/swiper.scss';
import { Footer, Header } from '@/widgets';
import { fonts } from '@/shared/static/font';
import { Raleway } from 'next/font/google';
import cn from 'classnames';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const raleway = Raleway({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={cn(fonts.variable, raleway.className)}>
        <MainProvider>
          <Header />
          <div className="wrapper">
            <div id="smooth-content">
              {children}
              <Footer />
            </div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
