export { Hero } from './hero';
export { Projects } from './projects';
export { Container } from './container';
export { MarqueeBlock } from './marquee-block';
export { Services } from './services';
export { Header } from './header';
export { Clients } from './clients';
export { News } from './news';
export { Footer } from './footer';
